name: CI

on:
  pull_request:
    branches: 
      - '*'
  push:
    branches-ignore:
      - 'release-*'
    tags-ignore:
      - '*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run checks
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y bzr
        make ci
